package contextInitParam;

import java.io.IOException;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/loginPage")
public class RegistrationLoginPage extends HttpServlet{
	
	@Override
	public void doGet(HttpServletRequest req, HttpServletResponse res) throws IOException {
		res.setContentType("text/html");
		res.getWriter().println("<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <title>Person Registration</title>\r\n"
				+ "\r\n"
				+ "    <style>\r\n"
				+ "        body {\r\n"
				+ "            font-family: Arial, sans-serif;\r\n"
				+ "            background: #f2f2f2;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .container {\r\n"
				+ "            width: 400px;\r\n"
				+ "            margin: 50px auto;\r\n"
				+ "            background: white;\r\n"
				+ "            padding: 25px;\r\n"
				+ "            border-radius: 8px;\r\n"
				+ "            box-shadow: 0 0 10px rgba(0,0,0,0.2);\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        h2 {\r\n"
				+ "            text-align: center;\r\n"
				+ "            margin-bottom: 20px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        label {\r\n"
				+ "            display: block;\r\n"
				+ "            margin-top: 12px;\r\n"
				+ "            font-weight: bold;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        input, select, textarea {\r\n"
				+ "            width: 100%;\r\n"
				+ "            padding: 8px;\r\n"
				+ "            margin-top: 5px;\r\n"
				+ "            border-radius: 4px;\r\n"
				+ "            border: 1px solid #ccc;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        textarea {\r\n"
				+ "            resize: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        button {\r\n"
				+ "            width: 100%;\r\n"
				+ "            margin-top: 20px;\r\n"
				+ "            padding: 10px;\r\n"
				+ "            background: #4CAF50;\r\n"
				+ "            color: white;\r\n"
				+ "            border: none;\r\n"
				+ "            font-size: 16px;\r\n"
				+ "            border-radius: 4px;\r\n"
				+ "            cursor: pointer;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        button:hover {\r\n"
				+ "            background: #45a049;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "<div class=\"container\">\r\n"
				+ "    <h2>Person Registration</h2>\r\n"
				+ "\r\n"
				+ "    <form action=\"save\" method=\"post\">\r\n"
				+ "\r\n"
				+ "        <label>Full Name</label>\r\n"
				+ "        <input type=\"text\" name=\"name\" placeholder=\"Enter full name\" required>\r\n"
				+ "\r\n"
				+ "        <label>Email</label>\r\n"
				+ "        <input type=\"email\" name=\"email\" placeholder=\"Enter email\" required>\r\n"
				+ "\r\n"
				+ "        <label>Phone Number</label>\r\n"
				+ "        <input type=\"text\" name=\"phone\" placeholder=\"Enter phone number\" required>\r\n"
				+ "\r\n"
				+ "        <label>Password</label>\r\n"
				+ "        <input type=\"password\" name=\"password\" placeholder=\"Enter password\" required>\r\n"
				+ "\r\n"
				+ "        <label>Age</label>\r\n"
				+ "        <input type=\"number\" name=\"age\" placeholder=\"Enter age\" required>\r\n"
				+ "\r\n"
				+ "        <label>Gender</label>\r\n"
				+ "        <select name=\"gender\" required>\r\n"
				+ "            <option value=\"\">Select gender</option>\r\n"
				+ "            <option>Male</option>\r\n"
				+ "            <option>Female</option>\r\n"
				+ "            <option>Other</option>\r\n"
				+ "        </select>\r\n"
				+ "\r\n"
				+ "        <label>Address</label>\r\n"
				+ "        <textarea name=\"address\" rows=\"3\" placeholder=\"Enter address\"></textarea>\r\n"
				+ "\r\n"
				+ "        <button type=\"submit\">Register</button>\r\n"
				+ "\r\n"
				+ "    </form>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n"
				+ "");
	}
}
